### PR TITLE
1512 Move ProcessModelApplication to src/test

### PR DESCRIPTION
**Pull request by constantin-ciobotaru**

### CODE REVIEW

**Comment by Salaboy** [comment]
@constantin-ciobotaru congrats on your first PR :) I don't see now the App class moved to the src/test, am I missing something?

**Comment by constantin-ciobotaru** [comment]
Yah, I also missed that when I looked first time in the PR changes :) : src/main/java/org/activiti/cloud/process/model/ProcessModelApplication was renamed to src/test/java/org/activiti/cloud/process/model/ProcessModelApplication

**Comment by Salaboy** [comment]
@constantin-ciobotaru you are right.. damn UI :)

**Comment by Salaboy** [comment]
@constantin-ciobotaru keep using this branch to move the process model service forward.. I will merge it when there is more meat to it, is that ok?

**Comment by Salaboy** [comment]
merged

**Pull request closed without merging**
